defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

monitor:
  value: "val/loss"
  mode: "min"

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "${..monitor.value}"
  mode: "${..monitor.mode}"
  save_last: True

early_stopping:
  patience: 16
  monitor: "${..monitor.value}"
  mode: "${..monitor.mode}"

model_summary:
  max_depth: 2