defaults:
  - model: default
  - data: default
  - paths: default
  - trainer: default
  - hydra: default
  - _self_

model:
  net:
    pretrained: false

safetensors_path: ???
image_dir: ???

task_name: predict

dataset:
  _target_: spineloc.data.dataset.InferenceImageDataset
  image_dir: ${image_dir}

dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 32
  num_workers: 4
  pin_memory: false